module.exports = [
    [ 'a tornado.  It\'s an F5, and full of cows' ],
    [ 'an actor' ],
    [ 'actors' ],
    [ 'a columnist' ],
    [ 'a person' ],
    [ 'people' ],
    [ 'a pocket full of kryptonite' ],
    [ 'a question' ],
    [ 'questions unfit for human ponderings' ],
    [ 'a refrigerator' ],
    [ 'some refrigerators' ],
    [ 'a saw' ],
    [ 'saws' ],
    [ 'a scorpion' ],
    [ 'scorpions' ],
    [ 'a bobcat. Heh.  Look at him.' ],
    [ 'a box of bobcats' ],
    [ 'a cave with some lewd cave paintings' ],
    [ 'a cougar' ],
    [ 'some cougars' ],
    [ 'a root' ],
    [ 'a sneeze' ],
    [ 'a staircase' ],
    [ 'a tire' ],
    [ 'tires.  They are on fire.' ],
    [ 'a vase' ],
    [ 'Anthropology' ],
    [ 'a beard of bees' ],
    [ 'education' ],
    [ 'mustard' ],
    [ 'work' ],
    [ 'a Canoe.  It leaks slightly' ],
    [ 'Canoes, in a \'V\' formation' ],
    [ 'a Church' ],
    [ 'a fox' ],
    [ 'foxes' ],
    [ 'a harbor' ],
    [ 'Meat' ],
    [ 'an ophthalmologist' ],
    [ 'a beggar' ],
    [ 'a cello', 'noun' ],
    [ 'cellos', 'noun' ],
    [ 'a detective' ],
    [ 'an eyelash' ],
    [ 'Fear' ],
    [ 'your Grandfather' ],
    [ 'a lion' ],
    [ 'some lions' ],
    [ 'a radiator' ],
    [ 'a fishmonger' ],
    [ 'an adamantine wafer' ],
    [ 'a laptop from 1998' ],
    [ 'a Motorola Droid.  The screen is cracked.' ],
    [ 'a BANH MI sandwich' ],
    [ 'a bubble' ],
    [ 'a Nuka-Cola' ],
    [ 'a Jolt Cola' ],
    [ '99 Luftbaloons' ],
    [ '100 dogecoin paper coins' ],
    [ 'the 100th Luftballon. It\'s popped.....' ],
    [ 'a hot pocket' ],
    [ 'a can of Coca-Cola, filled with Pepsi' ],
    [ 'real food' ],
    [ 'some bratwurst' ],
    [ 'a classic NES' ],
    [ 'a broken bottle of maple syrup' ],
    [ 'ebola.  Walk it off.' ],
    [ 'a glass of sharkleberry fin kool-aid' ]
];