module.exports = [
    '10 Downing Street Guard Chair',
    'Aalto armchair 406',
    'Adirondack chair',
    'Aeron chair',
    'Air chair',
    'Armchair',
    'Balans chair',
    'Ball chair',
    'Barrel chair',
    'Bar stool chair',
    'Bikini chair',
    'Bachelor\'s chair',
    'Balans chair',
    'Ball Chair',
    'Barcelona chair',
    'Bardic Chair',
    'Barrel chair',
    'Bar stool',
    'Bath chair',
    'Beach chair',
    'Bean bag',
    'Bench',
    'Bergère',
    'Bikini chair',
    'Bofinger chair',
    'Bosun\'s chair',
    'Breuer Chair',
    'Brewster Chair',
    'Bubble Chair',
    'Butterfly chair',
    'Campeche chair',
    'Cantilever chair',
    'Captain\'s chair',
    'Car chair',
    'Chaise longue',
    'Carver chair',
    'Chaise',
    'Chaise longue',
    'Chiavari chair',
    'Club chair',
    'Cogswell chair',
    'Corner chair',
    'Caquetoire ',
    'Curule chair',
    'Chesterfield chair',
    'Dante chair',
    'Deck chair',
    'Dentist chair',
    'Dining chair',
    'Director\'s chair',
    'Easy chair',
    'Eames Lounge Chair',
    'Egg chair',
    'Electric chair',
    'Emeco 1006',
    'Farthingale chair',
    'Fauteuil',
    'Fiddleback chair',
    'Fighting chair',
    'Folding chair',
    'Folding seat',
    'Friendship bench',
    'Gaming chair',
    'Garden Egg chair',
    'Glastonbury chair',
    'Glider',
    'Hassock',
    'High chair',
    'Inflatable chair',
    'Ironing Chair',
    'Jack and Jill',
    'Kneeling chair',
    'Knotted chair',
    'Ladderback chair',
    'Lambing chair',
    'Lawn chair',
    'Lierna',
    'Lift chair',
    'Lightweight wheelchair',
    'Litter',
    'Louis Ghost chair',
    'Monobloc chair',
    'Massage chair',
    'Morris chair',
    'Muskoka chair',
    'Navy chair',
    'No. 14 chair',
    'Nursing chair',
    'Office chair',
    'ON Chair',
    'Ottoman',
    'Ovalia Egg Chair',
    'Panton Chair',
    'Papasan chair',
    'Parsons chair',
    'Patio chair',
    'Peacock chair',
    'Pew stacker chair',
    'Planter\'s chair',
    'Poofbag chair',
    'Porter\'s chair',
    'Potty chair',
    'Pouffe',
    'Power chairs',
    'Pressback chair',
    'Pushchair or stroller',
    'Questionable Chair',
    'Reception chair',
    'Recliner',
    'Revolving chair',
    'Rex chair',
    'Rocking chair',
    'Saddle chair',
    'Savonarola chair',
    'Sedan chair',
    'Sgabello',
    'Shaker rocker',
    'Shaker tilting chair',
    'Shower chair',
    'Side chair',
    'Sit-stand chair',
    'Spinning chair',
    'Slumber chair',
    'Sling chair',
    'Stacking chair',
    'Steno chair',
    'Stool',
    'Sweetheart chair',
    'Swivel chairs',
    'Tarachair',
    'Tête-à-tête chair',
    'Throne',
    'Toilet chair',
    'Tuffet',
    'Tulip chair',
    'Turned chair',
    'Up 5',
    'Visitor\'s chair',
    'Voyeuse chair',
    'Wainscot Chair',
    'Watchman\'s chair',
    'Wassily Chair',
    'Wheelchair',
    'Wheeled computer chair',
    'Wicker chair',
    'Wiggle chair',
    'Windsor chair',
    'Wing chair',
    'Writing armchair',
    'X-chair',
    'Zaisu',
    'Zig-Zag Chai'
];