// https://en.wikipedia.org/wiki/List_of_cooking_techniques
const preparation = [
  'Backwoods cooked',
  'Baked',
  'Barbecued',
  'Blanched',
  'Boiled',
  'Braised',
  'Broasted',
  'Browned',
  'Candy maked',
  'Caramelized',
  'Carry over cooked',
  'Charbroiled',
  'Cheesemaked',
  'Red cooked',
  'Clay pot cooked',
  'Coddled',
  'Creamed',
  'Curdled',
  'Cured',
  'Deep fryed',
  'Deglazed',
  'Degreased',
  'Dough sheeted',
  'Dredged',
  'Dry roasted',
  'Dryed',
  'Dum pukht',
  'Dutch oven cooked',
  'Engine Cooked',
  'Fermented',
  'Flambéd',
  'Flattop grilled',
  'Canned',
  'Cured',
  'Home canned',
  'Fryed',
  'Chicken Fryed',
  'Gentle fryed',
  'Glazed',
  'Grilled',
  'Hibachi',
  'High-altitude cooked',
  'Hot salt fryed',
  'Indirect grilled',
  'Infused',
  'Jugged',
  'Juiced',
  'Low-temperature cooked',
  'Macerated',
  'Marinated',
  'Microwave cooked',
  'Mongolian barbecued',
  'Nixtamalized',
  'Outdoor cooked',
  'Pan fryed',
  'Parbaked',
  'Parboiled',
  'Pascalized',
  'Pasteurized',
  'Flash pasteurized',
  'Pickled',
  'Pig roastd',
  'Poached',
  'Pre-fermented',
  'Preservation',
  'Pressure cooked',
  'Pressure fryed',
  'Proofed',
  'Puréed',
  'Reduced',
  'Rendered',
  'Riced',
  'Roasted',
  'Robatayaki',
  'Rotisseried',
  'Sautéed',
  'Seared',
  'Seasoned',
  'Separated',
  'Shallow fryed',
  'Shrivelled',
  'Simmered',
  'Slow cooked',
  'Smoked',
  'Smothered',
  'Soured',
  'Sous-vide',
  'Spherified',
  'Steamed',
  'Steeped',
  'Stewed',
  'Stir fryed',
  'Stuffed',
  'Sugar panned',
  'Supreme',
  'Sweated',
  'Swissed',
  'Tandoori',
  'Tataki',
  'Tempered',
  'Tenderized',
  'Teriyaki',
  'Thermal cooked',
  'Thermized',
  'Thickened',
  'Turbo cooked',
  'Turkey fryed',
  'Wok cooked',
];

// https://en.wikipedia.org/wiki/List_of_commercially_important_fish_species
const fishTypes = [
  'Grass carp',
  'Peruvian anchoveta',
  'Silver carp',
  'Common carp',
  'Asari',
  'Japanese littleneck',
  'Manila clam',
  'Filipino Venus',
  'Japanese cockle',
  'Japanese carpet shell',
  'Alaska pollock',
  'Nile tilapia',
  'Whiteleg shrimp',
  'Bighead carp',
  'Skipjack tuna',
  'Catla',
  'Crucian carp',
  'Atlantic salmon',
  'Atlantic herring',
  'Chub mackerel',
  'Rohu',
  'Yellowfin tuna',
  'Japanese anchovy',
  'Largehead hairtail',
  'Atlantic cod',
  'European pilchard',
  'Capelin',
  'Jumbo flying squid',
  'Milkfish',
  'Atlantic mackerel',
  'Rainbow trout',
  'Giant tiger prawn',
  'Asian tiger shrimp',
  'Araucanian herring',
  'Chinese razor clam',
  'Agemaki clam',
  'Chinese mitten crab',
  'Wuchang bream',
  'Pacific oyster',
  'Japanese oyster',
  'Miyagi oyster',
  'Louisiana crawfish',
  'Red swamp crawfish',
  'Akiami paste shrimp',
  'Gulf menhaden',
  'Indian oil sardine',
  'Black carp',
  'European anchovy',
  'Northern snakehead',
  'Pacific cod',
  'Pacific saury',
  'Pacific herring',
  'Bigeye tuna',
  'Chilean jack mackerel',
  'Yellow croaker',
  'Haddock',
  'Gazami crab',
  'Amur catfish',
  'Japanese common catfish',
  'European sprat',
  'Pink salmon',
  'Mrigal carp',
  'Channel catfish',
  'Blood cockle',
  'Blue whiting',
  'Hilsa shad',
  'Daggertooth pike',
  'California pilchard',
  'Cape horse mackerel',
  'Pacific anchoveta',
  'Japanese flying squid',
  'Argentine shortfin squid',
  'Pollock',
  'Chinese softshell turtle',
  'Kawakawa',
  'Indian mackerel',
  'Asian swamp eel',
  'Yesso scallop',
  'Argentine hake',
  'Northern prawn',
  'Short mackerel',
  'Southern rough shrimp',
  'Southern African anchovy',
  'Pond loach',
  'Iridescent shark',
  'Mandarin fish',
  'Chinese perch',
  'Nile perch',
  'Round sardinella',
  'Japanese pilchard',
  'American sea scallop',
  'Bombay-duck',
  'Yellowhead catfish',
  'Korean bullhead',
  'Narrow-barred Spanish mackerel',
  'Albacore',
  'Madeiran sardinella',
  'Bonga shad',
  'Silver cyprinid',
  'Nile tilapia',
  'Longtail tuna',
  'Atlantic menhaden',
  'Giant tiger prawn',
  'North Pacific hake',
  'Atlantic horse mackerel',
  'Japanese jack mackerel',
  'Pacific thread herring',
  'Bigeye scad ',
  'Yellowstripe scad',
  'Chum salmon',
  'Antarctic krill',
  'Blue swimming crab',
  'Pacific sandlance',
  'Goldstripe sardinella',
];

module.exports = {
  preparation,
  fishTypes,
};
