module.exports = {
  hug: 'No.',
  sleep: '(- o - ) zzZ ☽',
  zzz: '(- o - ) zzZ ☽',
  fight: "(ง︡'-'︠)ง",
  levelSelect: 'B A B A ↑ ↓ B A ← → B A (start)',
  konami: '↑ ↑ ↓ ↓ ← → ← → B A (start)',
  rain: 'ヽ｀、ヽ｀ヽヽ｀、ヽ｀ヽヽ｀、ヽ｀ヽ(¬_¬ )ヽ｀、ヽ｀ヽ｀、ヽ｀',
  domo: '\\|°▿▿▿▿°|/',
  barrelroll: '(._.)  ( l: )  ( .-. )  ( :l )  (._.)',
  hedgehog: "(•ᴥ• )́`́'́`́'́⻍ ",
  lurk: '┬┴┬┴┤(･_├┬┴┬┴',
  lurkbear: '┬┴┬┴┤ʕ•ᴥ├┬┴┬┴',
  internet: 'ଘ(੭*ˊᵕˋ)੭* ̀ˋ ɪɴᴛᴇʀɴᴇᴛs',
  cornflakes:
    '❅ ❆ ❆ ❆ ❆ ❅ ❆ ❆ ❅ ❆ ❅ ❆ ❆ ❆ ❆ ❆ ❆ ❆ ❅ ❅ ❅ ❆ ❅ ❆ ❅ ❅ ❆ ❅ ❆ ❅ ❆ ❆ ❆ ❆ ❆ ❆ ❆ ❆ ❆ ❆',
  snowflakes:
    '❅ ❆ ❆ ❆ ❆ ❅ ❆ ❆ ❅ ❆ ❅ ❆ ❆ ❆ ❆ ❆ ❆ ❆ ❅ ❅ ❅ ❆ ❅ ❆ ❅ ❅ ❆ ❅ ❆ ❅ ❆ ❆ ❆ ❆ ❆ ❆ ❆ ❆ ❆ ❆',
  moonflakes:
    '☽ ❅ ❅ ❅ ☾ ❆ ❅ ☽ ❆ ❆ ☾ ❅ ☽ ☾ ❅ ❅ ☾ ❅ ☽ ☽ ❆ ☽ ❅ ❅ ☾ ☾ ❆ ☾ ❅ ☾ ☾ ❅ ❅ ☾ ❅ ☾ ❅ ❅ ☾ ❆',
  whale: 'https://www.youtube.com/watch?v=xo2bVbDtiX8',
  safety: 'https://www.youtube.com/watch?v=AjPau5QYtYs',
  tacos:
    'https://www.youtube.com/watch?v=W0-esOKooEE&index=28&list=RDHsKXvAymwUg',
  shrug: '¯\\_(ツ)_/¯',
  'yes!': '( ･ㅂ･)و ̑̑',
  'yas!': '(ˆڡˆ)v',
  'no!': '｡゜(｀Д´)゜｡',
  'why?!': 'ლ(ಠ_ಠლ)',
  'why!?': 'щ(ಥДಥщ)',
  '...': 'ಠ_ಠ',
  '…': 'ಠ_ಠ',
  facepalm: '(－‸ლ)',
  bot: 'I AM BOT\nINSERT DOGE',
  witchhunt: 'http://i.imgur.com/x63cdJW.jpg',
  whichhunt: 'whichever',
  wow: 'https://i.imgur.com/8rhlusE.gif',
  flipthetable: '(╯°□°）╯︵ ┻━┻',
  chilloutbro: '┬──┬ ノ( ゜-゜ノ)',
  putthetableback: '┬──┬ ノ( ゜-゜ノ)',
  vampire: '(°,..,°)',
  magic: '∴•:+*⁽⁽ଘ( ˊᵕˋ )ଓ⁾⁾*+:•*∴',
  pacman: '( *<)  • • • • • • •',
  dontcopythatfloppy: 'https://www.youtube.com/watch?v=up863eQKGUI',
  jackdawed: 'http://media.giphy.com/media/rhaLXOOimBGN2/giphy.gif',
  thoodle: 'thoodle-oo!!',
  doom:
    'https://popkey-assets.s3.amazonaws.com/original-7850ad06-df4d-4d4c-af8e-9bb1698496c2.gif',
  bravo: 'http://gifs.gifme.io/i/5b9e69d976.gif',
  _val: 'yes?',
  '_val?': 'yes?',
  '_val!': 'what?!',
  groan:
    'https://media.tenor.com/images/4bc3e89894c7e99560a32a0a9613cd44/tenor.gif',
};
